# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 245, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 75 oblique 14pt \"Cantarell\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.choose_translate_x = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_translate_x.setObjectName("choose_translate_x")
        self.verticalLayout_3.addWidget(self.choose_translate_x)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.choose_translate_y = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_translate_y.setObjectName("choose_translate_y")
        self.verticalLayout_4.addWidget(self.choose_translate_y)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choose_translate_z = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.choose_translate_z.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_translate_z.setObjectName("choose_translate_z")
        self.verticalLayout_2.addWidget(self.choose_translate_z)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("font: 75 oblique 14pt \"Cantarell\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.choose_rotate_x = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_rotate_x.setObjectName("choose_rotate_x")
        self.verticalLayout_7.addWidget(self.choose_rotate_x)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.choose_rotate_y = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_rotate_y.setObjectName("choose_rotate_y")
        self.verticalLayout_5.addWidget(self.choose_rotate_y)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.choose_rotate_z = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_rotate_z.setObjectName("choose_rotate_z")
        self.verticalLayout_6.addWidget(self.choose_rotate_z)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("font: 75 oblique 14pt \"Cantarell\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.choose_scale_x = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_scale_x.setObjectName("choose_scale_x")
        self.verticalLayout_9.addWidget(self.choose_scale_x)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.choose_scale_y = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.choose_scale_y.setObjectName("choose_scale_y")
        self.verticalLayout_10.addWidget(self.choose_scale_y)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.choose_scale_z = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.choose_scale_z.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_scale_z.setObjectName("choose_scale_z")
        self.verticalLayout_14.addWidget(self.choose_scale_z)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("font: 75 oblique 14pt \"Cantarell\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setAccessibleName("")
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_11.addWidget(self.checkBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_12.addWidget(self.checkBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_13.addWidget(self.checkBox_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.choose_projection = QtWidgets.QComboBox(self.centralwidget)
        self.choose_projection.setGeometry(QtCore.QRect(60, 770, 121, 31))
        self.choose_projection.setStyleSheet("font: 75 oblique 14pt \"Cantarell\";")
        self.choose_projection.setEditable(False)
        self.choose_projection.setObjectName("choose_projection")
        self.choose_projection.addItem("")
        self.choose_projection.addItem("")
        self.button_apply = QtWidgets.QPushButton(self.centralwidget)
        self.button_apply.setGeometry(QtCore.QRect(60, 680, 121, 41))
        self.button_apply.setStyleSheet("font: 75 oblique 14pt \"Cantarell\";")
        self.button_apply.setObjectName("button_apply")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 20, 841, 781))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.father_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.father_layout.setContentsMargins(0, 0, 0, 0)
        self.father_layout.setObjectName("father_layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Translação"))
        self.label_5.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "Y"))
        self.choose_translate_z.setText(_translate("MainWindow", "Z"))
        self.label_2.setText(_translate("MainWindow", "Rotação"))
        self.label_10.setText(_translate("MainWindow", "theta X"))
        self.label_8.setText(_translate("MainWindow", "theta Y"))
        self.label_9.setText(_translate("MainWindow", "theta Z"))
        self.label_3.setText(_translate("MainWindow", "Escala"))
        self.label_11.setText(_translate("MainWindow", "dX"))
        self.label_13.setText(_translate("MainWindow", "dY"))
        self.choose_scale_z.setText(_translate("MainWindow", "dZ"))
        self.label_4.setText(_translate("MainWindow", "Espelhamento"))
        self.checkBox_2.setText(_translate("MainWindow", " x-y"))
        self.checkBox.setText(_translate("MainWindow", " y-z"))
        self.checkBox_3.setText(_translate("MainWindow", " y-z"))
        self.choose_projection.setItemText(0, _translate("MainWindow", "Perspectiva"))
        self.choose_projection.setItemText(1, _translate("MainWindow", "Ortogonal"))
        self.button_apply.setText(_translate("MainWindow", "Aplicar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

